Repository snowone4426/yori_zip, pull requests merged in 2022-10, with the labels that each got.

#73 Feat/login
  src/main/java/dao/UserDAO.java
  src/main/java/dto/UserObj.java
  src/main/webapp/ex.jsp
  src/main/webapp/loginMain.jsp
  src/main/webapp/loginProcess.jsp
Labels: 원근

#74 Feat/detail product
  src/main/java/dao/RecipeDAO.java
  src/main/java/dao/RepleDAO.java
  src/main/webapp/IsLoggedIn.jsp
  src/main/webapp/ex.jsp
  src/main/webapp/loginMain.jsp
  src/main/webapp/loginProcess.jsp
  src/main/webapp/nav.jsp
  src/main/webapp/reple.jsp
  src/main/webapp/repleDeleteProcess.jsp
  src/main/webapp/repleEdit.jsp
  src/main/webapp/repleProcess.jsp
  src/main/webapp/star.jsp
Labels: 정은

#75 Feat/main
  src/main/java/dao/BannerDAO.java
  src/main/java/dao/PopularListDAO.java
  src/main/java/dao/ThemeListDAO2.java
  src/main/java/dto/BannerObj.java
  src/main/java/dto/PopularListDTO.java
  src/main/webapp/banner.jsp
  src/main/webapp/css/main.css
  src/main/webapp/images/difficulty.png
  src/main/webapp/images/recipe/1.jpg
  src/main/webapp/images/recipe/carrot.jpg
  src/main/webapp/images/recipe/hotcake.jpg
  src/main/webapp/images/score.png
  src/main/webapp/images/time.png
  src/main/webapp/main.js
  src/main/webapp/main.jsp
  src/main/webapp/popList.jsp
  src/main/webapp/searchPage.jsp
  src/main/webapp/themeList2.jsp
  src/main/webapp/type.js
Labels: 은선

#76 [정은] ADD | footer 수정 완료
  src/main/webapp/css/main.css
  src/main/webapp/footer.jsp
  src/main/webapp/nav.jsp
  src/main/webapp/reple.jsp
  src/main/webapp/repleEdit.jsp
Labels: 정은

#77 Feat/login
  src/main/java/dao/UserDAO.java
  src/main/webapp/emailCheck.jsp
  src/main/webapp/emailCheckProcess.jsp
  src/main/webapp/loginMain.jsp
  src/main/webapp/loginProcess.jsp
  src/main/webapp/logoutProcess.jsp
  src/main/webapp/memberMain.jsp
  src/main/webapp/memberProcess.jsp
  src/main/webapp/nav.jsp
  src/main/webapp/nickCheck.jsp
  src/main/webapp/nickCheckProcess.jsp
  src/main/webapp/policy.jsp
  src/main/webapp/pwdSearch.jsp
  src/main/webapp/pwdSearchProcess.jsp
Labels: 원근

#78 [은선] 오류 수정을 위한 commit
  src/main/java/dao/PopularListDAO.java
  src/main/java/dto/PopularListDTO.java
  src/main/webapp/nav.jsp
  src/main/webapp/searchPage.jsp
Labels: 은선

#79 Feat/main
  src/main/java/dao/SearchListDAO.java
  src/main/webapp/css/main.css
  src/main/webapp/main.js
  src/main/webapp/main.jsp
  src/main/webapp/nav.jsp
  src/main/webapp/searchPage.jsp
Labels: 은선

#81 Feat/main
  src/main/java/dao/SearchListDAO.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/searchPage.jsp
Labels: 은선

#82 Feat/detail product
  src/main/java/dao/PopularListDAO.java
  src/main/java/dao/RecipeDAO.java
  src/main/java/dao/RepleDAO.java
  src/main/java/dao/ReplePage.java
  src/main/java/dao/StarDAO.java
  src/main/java/dto/RecipeObj.java
  src/main/webapp/Starprocess.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/images/carrot.jpg
  src/main/webapp/loginMain.jsp
  src/main/webapp/nav.jsp
  src/main/webapp/recipeDetail.jsp
  src/main/webapp/reple.jsp
  src/main/webapp/repleProcess.jsp
  src/main/webapp/star.jsp
Labels: 정은

#83 Feat/detail product
  src/main/java/dao/RecipeDAO.java
  src/main/java/dao/RepleDAO.java
  src/main/java/dao/StarDAO.java
  src/main/java/dto/RecipeObj.java
  src/main/webapp/images/hotcake.jpg
  src/main/webapp/nav.jsp
  src/main/webapp/policy.jsp
  src/main/webapp/popList.jsp
  src/main/webapp/recipeDeleteProcess.jsp
  src/main/webapp/recipeDetail.jsp
  src/main/webapp/reple.jsp
  src/main/webapp/repleEdit.jsp
  src/main/webapp/repleProcess.jsp
  src/main/webapp/themeList2.jsp
Labels: 정은
